### ISSUE TITLE
Issues/Feature Questions

### ISSUE THREAD

**Issue by Icarus77** [codedotspectra/enhanceddiscord#1]
Hello, I enjoy your theme, but some aspects of it are kind of a downgrade from regular Discord. Namely:
- Color
- Members tab being less compact, so you see less members than with default discord
- Members tb having OFFLINE/ONLINE icons that are kind of redundant with the status dots being there too.
- Channel List not having any borders to distinguish sections like the voice channel info and regular channels.
- White window bar which glitches and isn't fully recolored if you edit CSS color
- Typing notification doesn't change color to match theme

Is there any way to use the default Discord member's tab and color scheme? I like how you move the chat box to allow for more space, but I'd like to change the things listed back to normal somehow.

**Comment by codedotspectra** [comment]
i don't have time to make a version just for you, maybe later

**Comment by codedotspectra** [comment]
To disable the member labels : simply delete the "label" part in the code
To switch back to the discord color scheme: use what's in the readme with these colors 
http://www.color-hex.com/color-palette/25362
