### ISSUE TITLE
A few questions from someone who doesn't know about CSS

### ISSUE THREAD

**Issue by LOuroboros** [codedotspectra/enhanceddiscord#2]
The theme looks pretty nice. I'm using enhancedDiscord-WallpaperVersion and I like how it looks.
I just wanted to ask some things:

1) Could you consider changing the scrollbars? They look just like in the vanilla Discord theme.
They're ugly and unfitting when using Enhanced Discord, in my opinion.
![firefox_2018-08-01_13-32-34](https://user-images.githubusercontent.com/4485172/43535380-32debff6-9590-11e8-91e2-d6e6640e5435.png)

2) Is there a way to shrink the size of the servers list's icons? They're way too big, again, in my opinion.

**EDIT:**

3) Links are being displayed with some of Discord's theme's background color in them. Any way to fix that?
![firefox_2018-08-01_14-15-03](https://user-images.githubusercontent.com/4485172/43537313-5c8c5b92-9595-11e8-9d9c-efd41570b178.png)

I'm using Enhanced Discord through Mozilla Firefox v59.0.3 with the Stylus v1.4.13 AddOn, just in case.
Thanks for reading and sorry for bothering. Have a nice day.

**Comment by codedotspectra** [comment]
The scrollbars are customized, your screenshot scrollbars are weirdly unafected by the theme :/

The links background will be changed in the 1.8 version, server icons may be also changed in 1.8
