### ISSUE TITLE
New Bugs

### ISSUE THREAD

**Issue by Icarus77** [codedotspectra/enhanceddiscord#3]
New Discord update seems to have messed up a few things: 
The area above the chat box is now much taller, looking similar to the default chat box.
- The server list seems to be missing its new message and selected server indicator.
- First server on server list is overlapping into the friend list button, making it hard to click.
- The "+" button to add a server seems to be misaligned.

Don't know if you're still committed to updating this theme, but wanted to inform you anyway.

**Comment by codedotspectra** [comment]
i'm already working on theses :) i just don't wanna update  every time i add a line of code, just be patient it'll come up soon.
Btw i haven't planned to stop updating this theme

**Comment by Icarus77** [comment]
Hey, thanks for the update, a lot of the changes are really cool! However, I am confused about what to remove in the code to remove the online and new channel labels. They kind of take up a lot of space next to the text.

Also how can I make the space between the members on the list a bit taller again? I use the radial status (circle around their avatars) and it the circle gets cut off with the new height: https://i.imgur.com/gjybg8x.png

Hope I am not being seen as a bit of a pest, just like to ask questions on how to fix things myself so I never have to ask in the future.
