### ISSUE TITLE
Search Box Bugs

### ISSUE THREAD

**Issue by infinityz780** [codedotspectra/enhanceddiscord#5]
Hello, i've noticed that the search box's color is still the same as the normal Discord's dark theme and the "Learn More" icon disappeared as well. Could you fix this?

![search box](https://user-images.githubusercontent.com/42277979/43970165-d397cf6a-9cf6-11e8-8fbc-7685a9ae7cde.jpg)

**Comment by codedotspectra** [comment]
This part is tricky to custom due to the fact that it disapear when its not focused. I managed to customize it but with a plugin so it may not be effective for everyone :c
